### ISSUE TITLE
Doesn't work on my account?

### ISSUE THREAD

**Issue by elfprince13** [gabipurcaru/followgraph#10]
Inputing my handle [elfprince13@mumak.app](https://mumak.app/@elfprince13), returns the following message:
> No results found. Please double check for typos in the handle, and ensure that you follow at least a few people to seed the search. Otherwise, try again later as Mastodon may throttle requests.

additionally, one 1 warning:
> Found 1 warnings:
> Error while retrieving followers for elfprince13@mumak.app.

Not sure why this would be happening as my social graph is available unauthenticated.

**Comment by wernersv** [comment]
Same here. I'm using an account on mastodon.online

**Comment by yllekz** [comment]
Same with infosec.exchange

**Comment by mephinet** [comment]
Same error message when using on my account, mephinet@wien.rocks. Javascript console reports:

```log
Get page: https://wien.rocks/api/v1/accounts/109264877250127387/following
index-62bb3d1e89a843df.js:1          GET https://wien.rocks/api/v1/accounts/109264877250127387/following 401
d @ index-62bb3d1e89a843df.js:1
await in d (async)
h @ index-62bb3d1e89a843df.js:1
j @ index-62bb3d1e89a843df.js:1
onSubmit @ index-62bb3d1e89a843df.js:1
eV @ framework-114634acb84f8baa.js:9
eW @ framework-114634acb84f8baa.js:9
(anonymous) @ framework-114634acb84f8baa.js:9
rn @ framework-114634acb84f8baa.js:9
rt @ framework-114634acb84f8baa.js:9
(anonymous) @ framework-114634acb84f8baa.js:9
oN @ framework-114634acb84f8baa.js:9
eF @ framework-114634acb84f8baa.js:9
ri @ framework-114634acb84f8baa.js:9
nV @ framework-114634acb84f8baa.js:9
nI @ framework-114634acb84f8baa.js:9
index-62bb3d1e89a843df.js:1 eeeee Error: HTTP request failed
    at d (index-62bb3d1e89a843df.js:1:919)
    at async h (index-62bb3d1e89a843df.js:1:1362)
    at async j (index-62bb3d1e89a843df.js:1:2438)
```
The request fails with a 401 and doesn't include any Authorization header...

**Comment by mephinet** [comment]
Honestly, after reading through the code and the [API documentation of the following endpoint](https://docs.joinmastodon.org/methods/accounts/#following), I'm not entirely sure how the code is supposed to work, as an Authorization is required for this endpoint, but [accountFollows](https://github.com/gabipurcaru/followgraph/blob/252e39e162969d799abd25ba99ab44689496ac5f/components/Content.tsx#L39) does not provide any...

**Comment by gabipurcaru** [comment]
@mephinet, the documentation is definitely confusing; it says "OAuth: Public", but then says the authorization header is required. Regardless, the actual API does not require the header, most of the time.

Problems may arise when either there's a non-standard Mastodon server or if it chooses to throttle the request. I'll look into mitigating this, thanks for flagging!

**Comment by blackspike** [comment]
or mastodon.cloud!

**Comment by mrehler** [comment]
Can Echo having issues over on Mastodon.cloud. Would love to make use of the service!

**Comment by blackspike** [comment]
Hmm both those are already checked/unchecked as your recommend on mastodon.cloud

**Comment by mattlehrer** [comment]
You're right. Sorry. It looks like mastodon.cloud does not allow access to the following list without an access token, even though it's public on the web.
